services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phoenix_app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    
  phoenix:
    build:
      context: ./phoenix-api
      dockerfile: ./../docker/phoenix/Dockerfile
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/phoenix_app
    depends_on:
      - db
    volumes:
      - ./phoenix-api:/app
    ports:
      - "4000:4000"
    env_file:
      - .env

  symfony:
    build:
      context: ./symfony-app
      dockerfile: ./../docker/symfony/Dockerfile
    expose:
      - "9000"
    environment:
      APP_ENV: dev
    volumes:
      - ./symfony-app:/var/www/html
    depends_on:
      - phoenix
    user: "${UID}:${GID}"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./symfony-app:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - symfony
volumes:
  db_data: